changes in timeouts and in custom command & adding cucumber structure
stelmaga/Cypress_First_Steps pull request #1
Opened 2022-10-27 11:19 UTC by stelmaga

2022-11-02 08:49 UTC, PDanielski commented on cypress/fixtures/user_data.json
> +{
👍

2022-11-03 09:23 UTC, PDanielski requested changes

2022-11-03 09:23 UTC, PDanielski commented on cypress/integration/E2E_tests.feature
> +  Scenario: Search flow
Not big deal, but generally the Scenario should represent a use case, so a name like `User searches for a given keyword` would be more clear. `flow` in this case have the same meaning as `Scenario`, so IMO written as it is, is similar to having `Scenario: Search scenario`, redundant.
Same for the other scenarios.

But it is a little bit nitpicking from my side

2022-11-03 09:23 UTC, PDanielski commented on cypress/integration/E2E_tests.feature
> +Feature: Example E2E tests
Consider splitting the tests in multiple feature files, if they span across multiple pages

2022-11-03 09:23 UTC, PDanielski commented on cypress/integration/E2E_tests/E2E_tests.js
> +import { Given, When, Then } from "cypress-cucumber-preprocessor/steps"
When defining cucumber statements you should thrive to as smaller dependencies with the actual tests as possible. The should be reusable as much as possible in multiple tests.
Because of that, I would group those in per page files.

2022-11-03 09:23 UTC, PDanielski commented on cypress/integration/E2E_tests/E2E_tests.js
> +And ('User clicks Create an account button', () => {
You don't need to use `And` here. In the feature file the keyword `And` is just converted to the keyword of the previous statement (When, Then, Given).
I am not sure it will even work like this.

2022-11-03 09:23 UTC, PDanielski commented on cypress/integration/E2E_tests/E2E_tests.js
> +    cy.url({ timeout: 12000 }).should("contain", "account-creation")
👍

2022-11-03 09:23 UTC, PDanielski commented on cypress/integration/E2E_tests/E2E_tests.js
> +    cy.verifyHeaderTitle("My account")
Still not a big fan of this `verifyHeaderTitle` because of the way the function is named, It is not clear what it is doing.

2022-11-03 09:23 UTC, PDanielski commented on cypress/integration/tests.js
> +        AuthenticationPage.fillEmailCreateField(RandomEmailGenerator.randomEmail());
👍

2022-11-03 09:23 UTC, PDanielski commented on cypress/integration/utils.js
> +class RandomEmailGenerator {
👍

2022-11-03 09:23 UTC, PDanielski commented on cypress/support/commands.js
> +before(() => {
I would not use this before hook here. I don't think we need to preload the fixture before all the tests. It could be done directly in the `correctSignUpForm` command.

`this.data` creates a layer of indirection which make more unclear the entire flow. Also IMO it is not very scalable when and if we will have more fixtures to work with.

2022-11-03 11:46 UTC, PDanielski commented on cypress/support/commands.js
> +    SignInForm.fillMobilePhone(this.data.mobilePhone)
```suggestion
Cypress.Commands.add('correctSignUpForm', function () {
cy.fixture("user_data.json").then( function (data) {
      SignInForm.fillFirstName(data.firstName);
    SignInForm.fillSecondName(data.secondName)
    SignInForm.fillPassword(data.password)
    SignInForm.fillCompany(data.company)
    SignInForm.fillAddress1(data.address1)
    SignInForm.fillCity(data.city)
    SignInForm.chooseState(data.state)
    SignInForm.fillPostcode(data.postcode)
    SignInForm.fillMobilePhone(data.mobilePhone)
        })
    
```

2022-11-04 13:20 UTC, stelmaga commented on cypress/integration/E2E_tests.feature
> +  Scenario: Search flow
I see, I've changed this tests names, to me more informative

2022-11-04 13:24 UTC, stelmaga commented on cypress/integration/E2E_tests.feature
> +Feature: Example E2E tests
As I am not going to write more test at this moment, I will stay with this one feature file. But I completely understand the need of creating more than one feature file in projects with more tests.

2022-11-04 13:36 UTC, stelmaga commented on cypress/integration/E2E_tests/E2E_tests.js
> +And ('User clicks Create an account button', () => {
I've changed these keywords to `When` here, but leave it as `And` in feature file.

2022-11-04 13:50 UTC, stelmaga commented on cypress/integration/E2E_tests/E2E_tests.js
> +    cy.verifyHeaderTitle("My account")
I've changed this to `verifyHeaderTitleContains`.

2022-11-04 14:04 UTC, stelmaga commented on cypress/support/commands.js
> +before(() => {
Completely agree with you on this :) Made some suggested changes! :)

2022-11-06 11:19 UTC, stelmaga commented on cypress/integration/E2E_tests/E2E_tests.js
> +import { Given, When, Then } from "cypress-cucumber-preprocessor/steps"
I've made some changes to make this cucumber statements more reusable so I split some of them and parametrised some of them.

2022-11-06 12:33 UTC, merged